umami-hep/puma

.github/workflows/publish.yaml, README.md, puma/__init__.py, setup.cfg, setup.py
* adds support to publish the project on PyPI
* One step closer to #1
=> Add support for publishing on PyPI

.pre-commit-config.yaml, examples/plot_basic_histogram.py, examples/plot_discriminant_scores.py, examples/plot_flavour_probabilities.py, examples/plot_fraction_scan.py, examples/plot_pie.py, examples/plot_pt_vs_eff.py, examples/plot_rocs.py, puma/__init__.py, puma/fraction_scan.py, puma/histogram.py, puma/plot_base.py, puma/roc.py, puma/tests/test_histogram.py, puma/tests/test_pie_chart.py, puma/tests/test_roc.py, puma/tests/test_var_vs_eff.py, puma/var_vs_eff.py, setup.cfg
* renaming according to pep8 (next step towards #11)
* disabling pylint from pre-commit hook
=> renaming according to pep8

changelog.md, puma/__init__.py
* first release, version `0.1.0`
=> Bump version to 0.1.0

changelog.md, puma/__init__.py
* first release (version `0.1.0`)
=> Bump version 0.1.0

docs/source/examples/dummy_data.md, docs/source/examples/histograms.md, docs/source/examples/index.md, docs/source/examples/pie_charts.md, docs/source/examples/rocs.md
* small fixes in the docs (i.e. removed some "umami" leftovers)
=> Remove "umami" leftovers in docs

.github/workflows/docker_build.yml, README.md, changelog.md, docker/Dockerfile, docker/Dockerfile_dev, puma/__init__.py
* set up the automatic build of puma Docker images
* Closes #28
=> Set up automatic Docker build

puma/tests/test_metrics.py
* adds unit tests for `metrics.py`
=> Adding unit tests for metrics.py

.github/workflows/docker_build.yml, README.md
* add badge from Docker build job to README
=> Add badge from docker build job

changelog.md, docs/source/examples/fraction_scan.md, examples/plot_fraction_scan.py
* Adding a documentation page for the FractionScan Plots
=> Adding example page for the fraction scan plots

docs/source/examples/index.rst
* includes fraction_scan in docs as follow up from https://github.com/umami-hep/puma/pull/38
=> Update index.rst to include fraction_scan in docs

.github/workflows/pages.yml, changelog.md, docs/build_docs.sh, docs/requirements.txt, docs/source/_static/switcher.json, docs/source/_templates/versioning.html, docs/source/conf.py, docs/source/dev_guidelines/docker.md, docs/source/redirect_index.html
* adds support for different versions in the sphinx docs
* I will add a button for version selection (instead of the version list on the left) in a follow-up PR, but for that to work I need this PR to be merged
* #3
=> WIP: Adding version support in docs

docs/build_docs.sh, docs/source/conf.py, puma/__init__.py
=> Fix version button in docs

puma/tests/test_plot_base.py, puma/tests/utils/test_logging.py, puma/utils/__init__.py
* removes code that was in `utils/__init__.py` but was actually moved to `utils/generate.py`
* two minor isort fixes
=> Remove duplicated code

changelog.md, puma/__init__.py
=> Bump version to 0.1.1

.github/workflows/testing.yml, README.md, changelog.md
* a comment that states the coverage is now added automatically for each commit on a pull request
* fixes the url that was provided in the README for direct install from GitHub
* #2
=> Adding coverage comment to pull request

docs/source/examples/index.md, examples/plot_pt_vs_eff.py, examples/plot_rocs.py
* fixing some typos in the examples
=> fixing small tutorial issues

puma/__init__.py
Update `puma.__version__` for release `v0.1.2`
=> Bump version to 0.1.2

README.md, changelog.md, puma/__init__.py
* Adds Zenodo badge to README
* Closes #35
=> Adding to Zenodo

.github/workflows/coverage.yml, .github/workflows/linting.yml, .github/workflows/pages.yml, .github/workflows/testing.yml, .github/workflows/update_todo_issue.yaml
* adds `on: pull_request` to many jobs of our pipeline, to make them also run for pull requests (`push` seems to only be triggered when pushing to a pull request within the upstream repo)
=> Optimise GitHub Actions workflows for Pull Requests

changelog.md, puma/__init__.py
=> Bump to version `v0.1.4`

puma/tests/test_metrics.py
* Add unit tests for `puma.metrics.calc_eff` and `puma.metrics.calc_rej`
=> Improve coverage

requirements.txt
* adding [testfixtures](https://pypi.org/project/testfixtures/) package for logger unit tests
Relates to #103
=> adding textfixtures package

changelog.md, puma/__init__.py
=> bump version to v0.1.6

changelog.md, puma/__init__.py
=> Bump version to 0.1.7

docs/requirements.txt
* add a version number for the sphinx theme
=> Add version number for sphinx theme

changelog.md, puma/__init__.py
=> Bump version to 0.1.8

.github/workflows/linting.yml, changelog.md, puma/tests/test_histogram.py, puma/tests/test_line_2d.py, puma/tests/test_metrics.py, puma/tests/test_pie_chart.py, puma/tests/test_plot_base.py, puma/tests/test_roc.py, puma/tests/test_var_vs_eff.py, puma/tests/utils/test_generate.py, puma/tests/utils/test_histogram_utils.py, puma/tests/utils/test_logging.py, puma/tests/utils/test_utils.py
* extending `pylint` to run also on the `tests` folder which was not the case so far
*
=> extending pylint also to unit tests

requirements.txt
* adding `tables==3.7.0` to requirements
=> adding tables as requirement

changelog.md, puma/__init__.py
=> Bump Version to 0.1.9

changelog.md, puma/__init__.py
=> Bump version to v0.2.0

changelog.md, puma/utils/__init__.py
=> Change legend label of "dijets"

changelog.md, puma/__init__.py
=> Bump version

changelog.md, puma/hlplots/results.py, puma/hlplots/tagger.py
=> HLAPI: Cast tagger scores to full precision 

changelog.md, puma/__init__.py
=> Bumping version to 0.2.2

changelog.md, puma/__init__.py
=> Bumping version to v0.2.3

changelog.md, puma/__init__.py
=> Bumping version to v0.2.4

changelog.md, puma/__init__.py
=> Bump Version to v0.2.5

changelog.md, puma/__init__.py
=> Bump to v0.2.6

changelog.md, puma/__init__.py
=> Bump version to v0.2.7

changelog.md, puma/__init__.py
=> Bump to version 0.2.8

.pre-commit-config.yaml, changelog.md, puma/histogram.py, puma/hlplots/results.py, puma/hlplots/tagger.py, puma/integrated_eff.py, puma/line_plot_2d.py, puma/metrics.py, puma/pie.py, puma/plot_base.py, puma/roc.py, puma/tests/hlplots/test_results.py, puma/tests/test_line_2d.py, puma/utils/discriminant.py, puma/utils/logging.py, puma/var_vs_eff.py, puma/var_vs_var.py
=> Update ruff version

.vscode/settings.json, changelog.md, examples/high_level_plots.py, puma/hlplots/results.py, puma/tests/hlplots/test_results.py, puma/var_vs_eff.py
* consistent fc scan colours
* spcify effs per ROC
=> consistent  fc scan colours

changelog.md, examples/high_level_aux_plots.py, puma/hlplots/aux_results.py, puma/tests/hlplots/test_aux_results.py
* Updates structure of aux results class to match recent changes to results class (easier for eventual yuma integration).
=> Update aux_results class

docs/examples/histograms.md, examples/plot_histogram_underoverflow.py
* Changed the docs for Underflow/overflow bins
* Changed the example which produces the plots in this part of the docs
The default of underoverflow option got changed from False to True and the docs not yet updated.
=> Update underoverflow docs

changelog.md, docs/hlapi/yuma.md, examples/plt_cfg_xbb.yaml, puma/hlplots/results.py, puma/tests/hlplots/test_results.py, requirements.txt
* Adds support for plotting taus as a background
* Adds support (requires atlas-ftag-tools update) for tautagging plots in yuma
* As a side effect of the above changes, can now also trivially plot Xbb plots. An example config is provided
=> Tauma - Taus in Yuma

puma/hlplots/results.py
=> Ignore ptau if missing from tagger discriminant

.github/workflows/testing.yml
=> Fix examples test

changelog.md, puma/hlplots/results.py
* Removing hardcoded plotting settings and make them available via kwargs
* Adding inline comments and doc-strings
* First steps for #292
=> Removing hardcoded kwargs from high-level plotting

changelog.md, puma/hlplots/results.py, puma/tests/hlplots/test_results.py
* Adding a few missing unit tests
=> Adding missing unit tests

changelog.md, puma/plot_base.py, puma/tests/test_plot_base.py, requirements.txt
* Adding support for `show()` command in command line and Jupyter application
* Provide new unit tests for the `PlotBase` class
=> Adding show() function support

changelog.md, puma/hlplots/results.py, puma/tests/hlplots/test_results.py
* Adding some missing unit test
* Removing unnecessary line from test
* Fixing a docstring
=> Fixing Coverage

changelog.md, docs/examples/tutorial-plotting.md
* changes in the tutorial markdown to fix spelling mistakes, changes in the reader of h5 files and update `dips` version
Tagging @afroch
=> Puma Tutorial Fixes
