umami-hep/puma

.github/workflows/linting.yml, .github/workflows/testing.yml, examples/plot_basic_histogram.py, examples/plot_flavour_probabilities.py, examples/plot_pie.py
* Running pylint now also for `./examples` folder
* Running now also examples in actions
=> enabling pylint for examples and run examples in CI

puma/histogram.py, puma/metrics.py, puma/plot_base.py, puma/roc.py, puma/var_vs_eff.py, setup.cfg
* stops ignoring `logging-fstring-interpolation` in pylint
* First step towards #11
=> Stop ignoring "logging-fstring-interpolation" in pylint

changelog.md, examples/plot_pt_vs_eff.py, puma/plot_base.py, puma/tests/test_histogram.py, puma/tests/test_var_vs_eff.py, puma/var_vs_eff.py
* Sets the default for the number of ratio panels to 0
* Closes #4
=> Set new default `n_ratio_panels=0`

.github/workflows/pages.yml, .github/workflows/testing.yml, README.md
* the output of the example scripts is now pushed to a branch called `examples-material`. This allows us to easily use these images in the README and docs (just use the raw/download link of the image)
* #1
=> Use example plots from this repo

changelog.md, puma/histogram.py, puma/tests/test_histogram.py
* Removing warning when adding more than one reference histograms (this is often what we want, since we have one reference histogram per flavour)
* Adding unit tests for cases where multiple reference histograms are provided *for the same flavour*
* Only use the default colour of a flavour if no colour was specified in a `puma.Histogram` object
=> Removing warning for multiple reference histograms + adding tests

changelog.md, puma/histogram.py
* Until now, both the legend label and the linecolour of a flavoured `puma.Histogram` were overwritten with the values from the global config. They can now be overwritten individually (i.e. changing the linecolour won't affect the default label and vice versa)
=> Fix that colour and label can be modified in case of flavoured histogram

puma/plot_base.py
* correction of warning message if the number of ratio panels is set to >= 1 put also the vertical split of the plot is set to true (in order to plot a pie chart)
=> correction of warning message

puma/histogram.py, puma/plot_base.py, puma/roc.py, puma/var_vs_eff.py, setup.cfg
From now on, the following pylint warnings are *not* ignored globally anymore
* too-many-arguments
* too-many-instance-attributes
* unspecified-encoding
* too-few-public-methods
* next step towards #11
=> pylint improvements

.github/workflows/coverage.yml, .github/workflows/testing.yml, puma/tests/test_histogram.py
This pull request adds another job to the CI that takes care of the coverage comment. This has two advantages:
1.   Running `pytest` without piping the output to a txt file, since otherwise the unit test job does not fail even if tests fail (it would just show up in the comment created by the bot)
2.   From now on, the coverage comment is only posted on pull requests
3.   The coverage comment is edited after a new commit is pushed instead of posting a new commit (check the last comment in this PR to see this)
=> Fix pytest job not failing

changelog.md, examples/plot_discriminant_scores.py, examples/plot_flavour_probabilities.py, puma/histogram.py, puma/tests/test_histogram.py
* The `ratio_group` property of `puma.Histogram` objects is no longer updated via the `flavour` argument. This is changed to avoid that users specify ratio_groups without knowing what they do.
* Removed `flavour` from the discriminant example plot
=> Remove that `ratio_group` is set via `flavour`

.github/workflows/coverage.yml
* only post the coverage comment for pull requests that are not from a fork (forks don't have write permission, so the job would fail)
=> Adding fork-check for coverage comment

changelog.md, puma/utils/__init__.py
* Changes the default labels of 
* `singlebjets` (`"$b$-jets"` -> `"single-$b$ jets"`)
* `singlecjets` (`"$c$-jets"` -> `"single-$c$ jets"`)
=> Change labels of single-b jets and single-c jets

changelog.md, puma/plot_base.py
* splits the `force` argument in `puma.PlotBase.set_log()` into `force_x` and `force_y`, which allows to force logscale on the axes separately
* Closes #53
=> Improve `set_log()` method of `puma.PlotBase`

.github/workflows/testing.yml
* with the current setup, the publish to pypi job was not triggered when a tag was created. This should be fixed with this
=> Fix that new tags trigger pypi publish

examples/plot_fraction_scan.py
* fixes wrong filename in output of example script, which is used in the docs. Fixes this:
=> Fix typo in example script

.github/workflows/docker_build.yml, changelog.md, docker/Dockerfile, requirements.txt
* adds `h5py` to the Docker images. This might be useful for users who want to plot h5files 
* update pipeline such that Docker images are always built, just the push step requires to be on the `main` branch or on a tag. This way we ensure that the build will not fail after merging a PR
=> Adding `h5py` to Docker images

puma/__init__.py
Adds `dev` to the version number (to make the 'latest' button show up correctly in the docs).
=> Change to `dev` version

changelog.md, puma/tests/utils/test_histogram_utils.py, puma/utils/histogram.py
* Fixes the histogram calculation when nan values are included in the histogram data
* Raises a logger warning with the number of nan (and +- infinity) values if there are any:
```bash
$ python examples/plot_basic_histogram.py 
WARNING:puma: Histogram values contain 2 nan values!
WARNING:puma: Histogram values contain 1 +-inf values!
```
=> Adding check and removal of nan values in histograms

changelog.md, puma/utils/__init__.py
* Adding boosted jet categories to the utils (label, colour) for Xbb
* Closes #137
=> Adding boosted categories for Xbb to utils

changelog.md, puma/utils/__init__.py
This pull request introduces the following changes.
* `dijets` category was replaced with the `QCD` category in the `flavour_categories`
* #167
=> Replace dijets category with QCD catergory

.github/workflows/docker_build.yml, README.md, changelog.md, docker/Dockerfile, docker/Dockerfile_dev, docs/source/dev_guidelines/docker.md
For some reason, the main docker image only installed `h5py`, which created problems as reported by @mtanasin. I am adding all the requirements here. We should think about removing the dev image as I don't really see the point of it... having a singe image with all the deps and an editable install would be much cleaner.
Thoughts @dkobylianskii @afroch @philippgadow?
=> Add all requirements to docker image

changelog.md, docs/source/examples/high_level_api.md, examples/high_level_plots.py, puma/fraction_scan.py, puma/hlplots/results.py, puma/hlplots/tagger.py, puma/tests/hlplots/test_results.py, puma/tests/hlplots/test_tagger.py, requirements.txt
* Add the fraction scan plots to the high level API
* `Tagger` now uses https://github.com/umami-hep/atlas-ftag-tools/ to compute discriminants
* Output filenames are set automatically in the HLAPI
* https://github.com/umami-hep/puma/issues/140
Todo:
=> Adding Fraction Scans to high level API

changelog.md, puma/plot_base.py, puma/roc.py, puma/var_vs_var.py
* FIxing an issue in the `plot_base`. If `apply_atlas_style` is true, but the `use_atlas_tag` is false, the ATLAS tag will be plotted because the argument is not correctly passed. Is fixed by passing directly the `self.use_atlas_tag` option instead of an extra command.
=> Fixing issue in use_atlas_tag

changelog.md, puma/histogram.py, puma/utils/__init__.py, requirements.txt
* Updating ATLAS-FTAG-Tools package to newest available version
* Update the Xbb tagging labels to accommodate the changes from [#35](https://github.com/umami-hep/atlas-ftag-tools/pull/35)
=> Updating ATLAS-FTAG-Tools package

changelog.md, puma/hlplots/results.py, puma/tests/hlplots/test_results.py
* Fix bug in HL fraction scan plot: move plot/savefig outside of the loop.
=> HL Fraction scan bugfix

puma/utils/generate.py
To support a slightly older version of numpy (which comes with the latest athena 23.0, LCG 102) u2s should be provided an np.dtype.
It's this same issue: https://github.com/numpy/numpy/issues/22428
=> numpy 1.21 u2s can't convert dtype

puma/roc.py
This change adds support to set a per curve reference to the ROC curves, besides a reference per reject class. This allows to make ROC curve comparisons between datasets, for example between two validation rounds:
This adds a parameter `reference_key` to `add_roc()`, so something like the following can be done:
```python
plot_roc = RocPlot(
n_ratio_panels=1,
ylabel="Background rejection",
xlabel="$b$-jet efficiency",
atlas_second_tag="$\\sqrt{s}=13$ TeV, EMTopo jets \n29th - 30th validation round ttbar, $f_{c}=0.018$",
figsize=(6.5, 6),
y_scale=1.4,
)
plot_roc.add_roc(
Roc(
sig_eff,
fastGN1_ujets_rej_r29,
n_test=n_jets_light_r29,
rej_class="ujets",
signal_class="bjets",
label="fastGN1 r29",
linestyle="dashed",
),
key="fastGN1_r29",
)
plot_roc.add_roc(
Roc(
sig_eff,
fastGN1_ujets_rej_r30, …
```
=> add support to set a per ROC reference for the ratios

changelog.md, puma/hlplots/results.py, puma/hlplots/tagger.py, puma/tests/hlplots/test_results.py
* Add the option to add specific cuts to each tagger, useful when making train/val/test comparisons
=> Add per tagger cuts to results

changelog.md, puma/roc.py
* Generalise ROC curve ratio grouping by adding the `ratio_group` parameter to the `ROC` class
* Revert explicit setting the ratio reference as implemented in #200 as it is not needed anymore
* #202
=> Generalise ROC curve ratio grouping

changelog.md, puma/integrated_eff.py, puma/metrics.py, puma/tests/test_metrics.py
* Improve the *efficiency* of the efficiency calculation
* Add weight support
* Fix possible input issue with `IntegratedEff` plot 
* #197
=> Add weight support for eff calculation

changelog.md, docs/source/examples/histograms.md, examples/plot_data_mc.py
* Adding documentation for Data/MC plots
* Closes #189
=> Draft: Adding documentation for Data/MC Plots

examples/high_level_plots.py, examples/plot_pt_vs_eff.py, puma/hlplots/results.py, puma/hlplots/tagger.py, puma/tests/hlplots/test_results.py, puma/tests/hlplots/test_tagger.py, puma/tests/test_var_vs_eff.py, puma/tests/test_var_vs_var.py, puma/var_vs_eff.py
* Rename the default outputs for 'peff' plots, to be more clear
* Renamed argument for peff plots 'fixed_eff_bin' -> 'flat_eff_bin' to reduce confusion between 'fixed WP' and 'flat efficiency'
* Introduce support in high-level API for plotting signal efficiency as a function of a variable, for a fixed background rejection per bin.
=> Improve performance per variable plots

changelog.md, puma/hlplots/results.py, puma/tests/hlplots/test_results.py, requirements.txt
This pull request introduces the following changes.
* Add NaN filtering to the loaded data in HL plots and warn the user about it.
* Update `atlas-ftag-tools` package
* #219
=> Add NaN filtering for HL plots

changelog.md, puma/metrics.py
Before that the cdf had n_data values ususally equidistantly spread in [0, 1] region which leads to a lot of problems with float arythmetic if n_data is around or greater 1_000_000 (empirically). I let the range be extended by casting data into floaat64
* Solves https://github.com/umami-hep/puma/issues/230
=> metric.weighted_percentile fixing bug connected to range of a float

changelog.md, puma/hlplots/aux_results.py, puma/hlplots/results.py, puma/hlplots/tagger.py, puma/tests/hlplots/test_aux_results.py, puma/tests/hlplots/test_results.py
* Add support for having multiple `VarVsEff` plots for different variables (e.g., `pt, eta`)
* #227
=> Add multiple perf_vars support

changelog.md, docs/source/examples/yuma.md, examples/plt_cfg.yaml, examples/taggers.yaml, puma/hlplots/__init__.py, puma/hlplots/configs.py, puma/hlplots/results.py, puma/hlplots/tagger.py, puma/hlplots/yuma.py, puma/hlplots/yutils.py, puma/tests/test_yuma.py, pyproject.toml
* `pip install -e .` now automatically installs deps in `requirements.txt`
* streamlining some yuma config to make it a thinner layer on top of results
* #223
=> Pyproject installl deps and yuma config cleanup

changelog.md, docs/source/examples/yuma.md, examples/plt_cfg.yaml, examples/taggers.yaml, puma/hlplots/configs.py, puma/hlplots/results.py, puma/hlplots/tagger.py, puma/hlplots/yuma.py, puma/tests/test_yuma.py
* Improvements to yuma config - using wherever possible class init args to directly configure things
* #223
=> Improve yuma config

changelog.md, puma/hlplots/configs.py
=> Allow yuma base path to work with tagger sample dir

changelog.md, puma/hlplots/configs.py
* Fix code to only plot specified tagger in plt_cfg.yaml when using yuma
* #223
=> Fix taggers selection configuration for yuma

puma/hlplots/yuma.py
* By default, assume the user wants to plot all taggers in the tagger config.
* However, if they do define a 'taggers' option in the plot config, then we only plot the desired plots.
*
*
=> Plot all taggers if no option specified

changelog.md, docs/source/examples/index.rst, docs/source/examples/tutorial-plotting.md
* Moving relevant [tutorial](https://ftag-docs.docs.cern.ch/software/tutorials/tutorial-plotting/) from FTAG documentation here so that they can be easily updated and stay relevant.
=> Moving tutorial from FTAG documentation

docs/source/examples/index.md
* changing the dataframe format to avoid crash
* Example in "Some basics before plotting" crashes out of the box
=> fixing crash in example - df format

changelog.md, puma/hlplots/aux_results.py, puma/utils/vertexing.py
* Removed line that eliminated SV candidates for GN2 if less than 2 (rather than 1) tracks were marked as fromHF
* Fixed a bug with plot labels not showing correctly for some aux task plots
=> Minor bugfix in HF vertex merging

changelog.md, puma/hlplots/results.py, puma/hlplots/yuma.py, puma/tests/hlplots/test_results.py, puma/tests/hlplots/test_yuma.py
* Better filenames when using the high level API
* Plots are put into nested dir
* #244
=> Better filenames when using the high level API

changelog.md, puma/plot_base.py
When setting the ymin_ratio and ymax_ratio, the originial condition 'if self.ymin_ratio[i]' evaluates to False if the values is zero. I fixed the issue by changing the condition to 'if self.ymin_ratio[i] is not None'.
=> Fix setting ymin_ratio (and ymax_ratio) in PlotBase if it is zero

examples/plt_cfg.yaml, puma/hlplots/results.py, puma/hlplots/yuma.py, puma/tests/hlplots/test_yuma.py
* Fixed the yuma example config for 'scan' type plots
* Fixed issue where 'backgrounds' weren't getting converted to 'Flavour' objects
=> Fix yuma fscan

changelog.md, puma/hlplots/aux_results.py
* Fixes treatment of padded tracks when calculating CM
=> Track origin confusion matrix padding fix

changelog.md, docs/examples/confusion_matrix.md, puma/hlplots/aux_results.py, puma/tests/utils/test_confusion_matrix.py, puma/utils/confusion_matrix.py
* Changed the definition of fake rate, from
```math
f \triangleq \frac{\hat{N}_{\bar{c}}}{N_c}
```
to
```math
f \triangleq \frac{\hat{N}_{\bar{c}}}{\hat{N}_c}
```
* Wrote the efficiency and fake rate definitions in the CM docs
* Uniformed the float precision of the efficiencies and fake rates to the one of the CM entries
=> Redefine fake rate

changelog.md, puma/hlplots/aux_results.py, puma/matshow.py
* No colour bar by default for confusion matrices
* Better ylabel axis names for vertexing plots
cc @jmw464 @LucioDerin
=> Minor update for auxtask plots

changelog.md, docs/examples/confusion_matrix.md, docs/examples/precision_recall.md, docs/hlapi/high_level_aux_api.md, examples/confusion_matrix_examples.py, examples/precision_recall_examples.py, puma/hlplots/aux_results.py, puma/tests/utils/test_confusion_matrix.py, puma/tests/utils/test_precision.py, puma/tests/utils/test_recall.py, puma/utils/confusion_matrix.py, puma/utils/precision_score.py, puma/utils/recall_score.py
* Added functions to compute the per-class precision and recall scores
* Added the scores on the Track Origin's confusion matrix plot
=> Precision and Recall scores

puma/hlplots/aux_results.py, puma/utils/vertexing.py
* Allows passing purity and recall requirements from the `plot_var_vtx_perf` to make it easier to make plots given different requirements
* Changes a requirement definition of recall/purtiy to now be `>=` instead of just `>`
=> Improved control in high-level interface for auxiliary plots

changelog.md, puma/hlplots/tagger.py, puma/tests/hlplots/test_aux_results.py, puma/tests/hlplots/test_tagger.py, puma/utils/generate.py
* Updated names of aux task output variables to match Salt
=> Update names of aux variables

changelog.md, puma/__init__.py
=> Bump version to 0.3.6

changelog.md, puma/hlplots/aux_results.py
* Fixes inconsistent use of kwargs in plot_vertex_mass function
* Increases number of bins in mass difference plots
=> Minor updates to plot_vertex_mass function

changelog.md, puma/__init__.py, requirements.txt
* Upgrade [atlas-ftag-tools](https://github.com/umami-hep/atlas-ftag-tools) version to v0.2.8
* Bump version for new release to incorporate changes from [atlas-ftag-tools](https://github.com/umami-hep/atlas-ftag-tools)
=> Upgrade atlas-ftag-tools version

changelog.md, puma/hlplots/aux_results.py, puma/hlplots/results.py, puma/tests/hlplots/test_yuma.py
* Use pdfs by default in the HLAPI
=> Default to pdf plots in the HLAPI

changelog.md, puma/histogram.py
* Fixes an issue when using the stacked histograms without error bars
* Closes #301
Tagging @jackerschott
=> Fixing ratio calculation issue when using no error band

changelog.md, puma/utils/confusion_matrix.py
* Adds some extra flexibility to the confusion matrix code if labels are non-consecutive or some label categories are missing completely in either true or predicted arrays.
=> Minor update to confusion matrix

changelog.md, puma/hlplots/aux_results.py, puma/hlplots/tagger.py, puma/utils/vertexing.py
* add a comment about producing track assignment recall and purity plots (should disable vertex quality requirements)
* improve atlas tag format
* add option to disable only the heavy flavour track requirement for GN2
=> Small fixes and improvements for vertexing plots

changelog.md, puma/hlplots/results.py
* Fixed bug where signal discriminant distribution was not plotted in discriminant plots
* Added option to plot ROC curve for flavours not included in all taggers (useful for DL1 vs. GN2 comparisons)
=> Fixes and updates to results class

changelog.md, requirements.txt
* Update `atlas-ftag-tools` to `v0.2.12`
=> Update atlas-ftag-tools package

changelog.md, requirements.txt
* Bump `atlas-ftag-tools` version to `v0.2.13`
=> Bumping atlas-ftag-tools version to v0.2.13

changelog.md, docs/examples/histograms.md, examples/plot_basic_histogram.py, examples/plot_histograms_from_files.py, examples/plot_iterative_histogram.py, puma/histogram.py, puma/tests/test_histogram.py
* Adding `update()` function to the `Histogram` class. Histograms can now be filled iteratively with this. The first init of the class must be done with the first batch, but afterwards you can simply do `Histogram.update()`.
=> Adding Iterative Filling for Histogram Class

changelog.md, requirements.txt
* Update `atlas-ftag-tools` to `0.2.16`
=> Update `atlas-ftag-tools` to `0.2.16`

changelog.md, puma/hlplots/__init__.py, puma/hlplots/results.py, puma/tests/hlplots/test_results.py
* Fixing the separation of the kwargs in the high-level plots. The kwargs provided to the function are now correctly split for the plot object and the curve object(s).
=> Fixing kwargs Separation in High-Level Plots
